version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- cmd: dotnet pack -c Release AsyncProcessExecutor/AsyncProcessExecutor.csproj
deploy:
- provider: NuGet
  api_key:
    secure: d1XW1IBAU4GVpSt5/P58qVTuaRbMU2EtT1XpYGGAsrWzb//dzFkJGYO1HONsQ/dW